services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=k%amu!l%due_2t1_mbg57(0ivzdz4$680xy6lttxof(g&f09$u
      - DATABASE_URL=sqlite:///db.sqlite3
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped